"""PUBLIC synthetic lab TLS material, never production credentials.

Generated from deliberately public P-256 scalars 37/41/43. The fixed certificates
are valid 2020-01-01 through 2100-01-01. Runtime needs only Python/OpenSSL;
cryptography was used once to author these fixtures, not as a dependency.
"""

SERVER_CERT_PEM = b'-----BEGIN CERTIFICATE-----\nMIIBwzCCAWmgAwIBAgICA+owCgYIKoZIzj0EAwIwJDEiMCAGA1UEAwwZSGFyYm9y\nRGVzayBQVUJMSUMgVEVTVCBDQTAgFw0yMDAxMDEwMDAwMDBaGA8yMTAwMDEwMTAw\nMDAwMFowGjEYMBYGA1UEAwwPaGFyYm9yZGVzay50ZXN0MFkwEwYHKoZIzj0CAQYI\nKoZIzj0DAQcDQgAEZ6a+wkDe4GUc8ljS5s/oqmBnxcPUF1pZOn3mlJldL6LeaStw\nItExWGwkm0lGTUSZFULH7iCaymxJwkzhRB/u1aOBkjCBjzAMBgNVHRMBAf8EAjAA\nMB0GA1UdDgQWBBS2oZHZYEbyAr6rsJQONrc4/jUJZTAfBgNVHSMEGDAWgBRL+s3Z\n+hVHpbjOOlrpTw/OgyAFcjAaBgNVHREEEzARgg9oYXJib3JkZXNrLnRlc3QwEwYD\nVR0lBAwwCgYIKwYBBQUHAwEwDgYDVR0PAQH/BAQDAgeAMAoGCCqGSM49BAMCA0gA\nMEUCICKNp0cWgqyFURwM+0aC+2NSWn+EnfaSSr8cA1GmVw8cAiEAiOWoSLW5+UUw\nOI+lE7wKput8jchwmp40RzAlxce3hgo=\n-----END CERTIFICATE-----\n'
UNTRUSTED_SERVER_CERT_PEM = b'-----BEGIN CERTIFICATE-----\nMIIBxjCCAWygAwIBAgICA+wwCgYIKoZIzj0EAwIwJzElMCMGA1UEAwwcSGFyYm9y\nRGVzayBVTlRSVVNURUQgVEVTVCBDQTAgFw0yMDAxMDEwMDAwMDBaGA8yMTAwMDEw\nMTAwMDAwMFowGjEYMBYGA1UEAwwPaGFyYm9yZGVzay50ZXN0MFkwEwYHKoZIzj0C\nAQYIKoZIzj0DAQcDQgAEZ6a+wkDe4GUc8ljS5s/oqmBnxcPUF1pZOn3mlJldL6Le\naStwItExWGwkm0lGTUSZFULH7iCaymxJwkzhRB/u1aOBkjCBjzAMBgNVHRMBAf8E\nAjAAMB0GA1UdDgQWBBS2oZHZYEbyAr6rsJQONrc4/jUJZTAfBgNVHSMEGDAWgBSs\npPOq0fbMfpUr0GCMESbENeYqrTAaBgNVHREEEzARgg9oYXJib3JkZXNrLnRlc3Qw\nEwYDVR0lBAwwCgYIKwYBBQUHAwEwDgYDVR0PAQH/BAQDAgeAMAoGCCqGSM49BAMC\nA0gAMEUCIQDBdUj2s0qETu8LX+YJPAgEVn9bk/SnN+WOu1qvFAhimgIgGz1l//BA\noU1xi/vCye3OvrNUTkL03qODgxHkIAYS7Yo=\n-----END CERTIFICATE-----\n'
SERVER_KEY_PEM = b'-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgAAAAAAAAAAAAAAAA\nAAAAAAAAAAAAAAAAAAAAAAAAACmhRANCAARnpr7CQN7gZRzyWNLmz+iqYGfFw9QX\nWlk6feaUmV0vot5pK3Ai0TFYbCSbSUZNRJkVQsfuIJrKbEnCTOFEH+7V\n-----END PRIVATE KEY-----\n'
